Repository jenkinsci/junit-plugin, pull requests merged in 2020-10, with the labels that each got.

#172 Update parent POM
  pom.xml
Labels: chore

#174 Bump bom + baseline to 2.222.x
  pom.xml
Labels: chore

#50 [JENKINS-36305] Fix TestObject url in order to fix TestActions links
  src/main/java/hudson/tasks/junit/TestObject.java
  src/main/java/hudson/tasks/test/TestObject.java
  src/main/resources/hudson/tasks/junit/CaseResult/list.jelly
  src/main/resources/hudson/tasks/junit/ClassResult/list.jelly
  src/main/resources/hudson/tasks/junit/History/index.jelly
  src/main/resources/hudson/tasks/test/MetaTabulatedResult/list.jelly
  src/test/java/hudson/tasks/test/TestObjectTest.java
Labels: needs-review

#171 Remove unneeded API in pluggable storage
  src/main/java/hudson/tasks/junit/ClassResult.java
  src/main/java/io/jenkins/plugins/junit/storage/TestResultImpl.java
  src/test/java/io/jenkins/plugins/junit/storage/TestResultStorageJunitTest.java
Labels: enhancement

#189 Allow setting custom checks name
  README.md
  src/main/java/hudson/tasks/junit/JUnitResultArchiver.java
  src/main/java/hudson/tasks/junit/JUnitTask.java
  src/main/java/hudson/tasks/junit/TestResultAction.java
  src/main/java/hudson/tasks/junit/pipeline/JUnitResultsStep.java
  src/main/java/io/jenkins/plugins/junit/checks/JUnitChecksPublisher.java
  src/main/resources/hudson/tasks/junit/JUnitResultArchiver/config.jelly
  src/main/resources/hudson/tasks/junit/JUnitResultArchiver/help-checksName.html
  src/main/resources/hudson/tasks/junit/pipeline/JUnitResultsStep/help-checksName.html
  src/test/java/io/jenkins/plugins/junit/checks/JUnitChecksPublisherTest.java
  src/test/java/io/jenkins/plugins/junit/storage/TestResultStorageJunitTest.java
Labels: enhancement
