Repository jenkinsci/junit-plugin, pull requests merged in 2020-09, with the labels that each got.

#152 Avoid NPE from CaseResult.getName()
  src/main/java/hudson/tasks/junit/CaseResult.java
  src/test/java/hudson/tasks/junit/CaseResultTest.java
Labels: bug

#156 Bump echarts-version
  pom.xml
Labels: dependencies

#155 UI and descriptors for pluggable storage
  pom.xml
  src/main/java/hudson/tasks/junit/CaseResult.java
  src/main/java/hudson/tasks/junit/ClassResult.java
  src/main/java/hudson/tasks/junit/History.java
  src/main/java/hudson/tasks/junit/JUnitParser.java
  src/main/java/hudson/tasks/junit/JUnitResultArchiver.java
  src/main/java/hudson/tasks/junit/PackageResult.java
  src/main/java/hudson/tasks/junit/TestResult.java
  src/main/java/hudson/tasks/junit/TestResultAction.java
  src/main/java/hudson/tasks/junit/storage/package-info.java
  src/main/java/hudson/tasks/test/TestResultProjectAction.java
  src/main/java/io/jenkins/plugins/junit/storage/FileJunitTestResultStorage.java
  src/main/java/io/jenkins/plugins/junit/storage/JunitTestResultStorage.java
  src/main/java/io/jenkins/plugins/junit/storage/JunitTestResultStorageConfiguration.java
  src/main/java/io/jenkins/plugins/junit/storage/JunitTestResultStorageDescriptor.java
  src/main/java/io/jenkins/plugins/junit/storage/TestResultImpl.java
  src/main/resources/io/jenkins/plugins/junit/storage/JunitTestResultStorageConfiguration/config.jelly
  src/main/resources/io/jenkins/plugins/junit/storage/Messages.properties
  src/test/java/io/jenkins/plugins/junit/storage/JunitTestResultStorageConfigurationTest.java
  src/test/java/io/jenkins/plugins/junit/storage/TestResultStorageJunitTest.java
  src/test/resources/io/jenkins/plugins/junit/storage/configuration-as-code-expected.yml
  src/test/resources/io/jenkins/plugins/junit/storage/configuration-as-code.yml
Labels: enhancement

#158 Fix history page mixed tabs and spaces
  src/main/resources/hudson/tasks/junit/History/index.jelly
Labels: skip-changelog

#159 Load pluggable storage config from XML
  src/main/java/io/jenkins/plugins/junit/storage/JunitTestResultStorageConfiguration.java
Labels: skip-changelog

#161 Fix missing sidebar with pluggable storage on test report
  src/main/java/hudson/tasks/junit/TestResult.java
  src/main/java/io/jenkins/plugins/junit/storage/TestResultImpl.java
  src/test/java/io/jenkins/plugins/junit/storage/TestResultStorageJunitTest.java
Labels: bug

#162 Implement test report table for pluggable storage
  src/main/java/hudson/tasks/junit/PackageResult.java
  src/main/java/hudson/tasks/junit/TestResult.java
  src/main/java/io/jenkins/plugins/junit/storage/TestResultImpl.java
  src/test/java/io/jenkins/plugins/junit/storage/TestResultStorageJunitTest.java
Labels: enhancement

#164 Pluggable storage: More test report fixes
  src/main/java/hudson/tasks/junit/CaseResult.java
  src/main/java/hudson/tasks/junit/SuiteResult.java
  src/main/java/hudson/tasks/junit/TestResult.java
  src/main/java/io/jenkins/plugins/junit/storage/TestResultImpl.java
  src/test/java/io/jenkins/plugins/junit/storage/TestResultStorageJunitTest.java
Labels: enhancement

#166 Add initial benchmark
  .gitignore
  src/test/java/io/jenkins/plugins/junit/storage/benchmarks/BenchmarkRunner.java
  src/test/java/io/jenkins/plugins/junit/storage/benchmarks/TrendGraphBenchmark.java
Labels: tests

#167 Find last build with action if current is null
  src/main/java/hudson/tasks/test/TestResultProjectAction.java
Labels: bug

#170 Pluggable storage: Add stdout, stderr, stacktrace, fix caseresult loading
  src/main/java/hudson/tasks/junit/CaseResult.java
  src/main/java/hudson/tasks/junit/PackageResult.java
  src/test/java/io/jenkins/plugins/junit/storage/TestResultStorageJunitTest.java
Labels: enhancement
