Repository jenkinsci/junit-plugin, pull requests merged in 2020-07, with the labels that each got.

#134 Convert trend to ECharts
  pom.xml
  src/main/java/hudson/tasks/test/AbstractTestResultAction.java
  src/main/java/hudson/tasks/test/TestResultActionIterable.java
  src/main/java/hudson/tasks/test/TestResultProjectAction.java
  src/main/java/hudson/tasks/test/TestResultTrendChart.java
  src/main/java/hudson/tasks/test/TestResultTrendSeriesBuilder.java
  src/main/resources/hudson/tasks/test/TestResultProjectAction/floatingBox.jelly
  src/test/java/hudson/tasks/junit/TestResultPublishingTest.java
Labels: enhancement

#135 JENKINS-63113 use (?) as test name when empty in original report file
  src/main/java/hudson/tasks/junit/CaseResult.java
  src/test/java/hudson/tasks/junit/TestResultTest.java
  src/test/resources/hudson/tasks/junit/junit-report-empty-testcasename.xml
Labels: enhancement

#126 Cleanup old code
  src/main/java/hudson/tasks/junit/Helper.java
  src/main/java/hudson/tasks/junit/History.java
  src/main/java/hudson/tasks/junit/JUnitParser.java
  src/main/java/hudson/tasks/junit/PackageResult.java
  src/main/java/hudson/tasks/junit/TestDataPublisher.java
  src/main/java/hudson/tasks/junit/TestResult.java
  src/main/java/hudson/tasks/junit/TestResultAction.java
  src/main/java/hudson/tasks/test/AggregatedTestResultPublisher.java
  src/main/java/hudson/tasks/test/PipelineBlockWithTests.java
  src/main/java/hudson/tasks/test/SimpleCaseResult.java
  src/main/java/hudson/tasks/test/TabulatedResult.java
  src/main/java/hudson/tasks/test/TestObject.java
  src/main/java/hudson/tasks/test/TestResultProjectAction.java
Labels: chore

#97 [JENKINS-30413] Fix test age calculation when same test name exists in different package
  src/main/java/hudson/tasks/junit/CaseResult.java
  src/main/java/hudson/tasks/junit/SuiteResult.java
  src/test/java/hudson/tasks/junit/CaseResultTest.java
  src/test/java/hudson/tasks/junit/SuiteResultTest.java
  src/test/java/hudson/tasks/junit/TestResultTest.java
  src/test/resources/hudson/tasks/junit/JENKINS-30413.xml
Labels: bug

#136 JENKINS-62775: Increase spacing between "Older" and "Newer" buttons
  src/main/resources/hudson/tasks/junit/History/index.jelly
Labels: bug

#131 JENKINS-48583 Remove test result deduplication logic
  src/main/java/hudson/tasks/junit/TestResult.java
  src/test/java/hudson/tasks/junit/TestResultTest.java
  src/test/resources/hudson/tasks/junit/JENKINS-12457/TestSuite_b_nonduplicate.xml
  src/test/resources/hudson/tasks/junit/JENKINS-48583/TEST-com.sample.test.TestMessage.xml
  src/test/resources/hudson/tasks/junit/JENKINS-48583/TEST-com.sample.test.TestMessage2.xml
  src/test/resources/hudson/tasks/junit/JENKINS-48583/TESTS-TestSuites.xml
Labels: bug
