Repository jenkinsci/junit-plugin, pull requests merged in 2020-08, with the labels that each got.

#138 JENKINS-62912 Improved tables to divs compat
  src/main/resources/hudson/tasks/test/AggregatedTestResultPublisher/config.jelly
  src/main/resources/lib/hudson/test/blockWrapper.jelly
Labels: chore

#140 JENKINS-63339 Fix aggregated report trend
  src/main/java/hudson/tasks/test/TestResultTrendSeriesBuilder.java
Labels: bug

#141 External storage - Part 1
  pom.xml
  src/main/java/hudson/tasks/junit/CaseResult.java
  src/main/java/hudson/tasks/junit/ClassResult.java
  src/main/java/hudson/tasks/junit/History.java
  src/main/java/hudson/tasks/junit/JUnitParser.java
  src/main/java/hudson/tasks/junit/JUnitResultArchiver.java
  src/main/java/hudson/tasks/junit/PackageResult.java
  src/main/java/hudson/tasks/junit/SuiteResult.java
  src/main/java/hudson/tasks/junit/TestResult.java
  src/main/java/hudson/tasks/junit/TestResultAction.java
  src/main/java/hudson/tasks/junit/TestResultSummary.java
  src/main/java/hudson/tasks/junit/pipeline/JUnitResultsStepExecution.java
  src/main/java/hudson/tasks/junit/storage/TestResultImpl.java
  src/main/java/hudson/tasks/junit/storage/TestResultStorage.java
  src/main/java/hudson/tasks/junit/storage/package-info.java
  src/main/java/hudson/tasks/test/AbstractTestResultAction.java
  src/main/java/hudson/tasks/test/TestObject.java
  src/test/java/hudson/tasks/junit/JUnitResultArchiverTest.java
  src/test/java/hudson/tasks/junit/pipeline/JUnitResultsStepTest.java
  src/test/java/hudson/tasks/junit/storage/TestResultStorageTest.java
Labels: enhancement

#143 Pluggable storage trend chart
  src/main/java/hudson/tasks/junit/TestResultSummary.java
  src/main/java/hudson/tasks/junit/TrendTestResultSummary.java
  src/main/java/hudson/tasks/junit/storage/TestResultImpl.java
  src/main/java/hudson/tasks/test/TestResultProjectAction.java
  src/main/java/hudson/tasks/test/TestResultTrendChart.java
  src/main/java/hudson/tasks/test/TestResultTrendSeriesBuilder.java
  src/test/java/hudson/tasks/junit/storage/TestResultStorageTest.java
Labels: enhancement

#144 Update database plugins
  pom.xml
Labels: dependencies

#145 Add persisting duration
  src/main/java/hudson/tasks/junit/CaseResult.java
  src/test/java/hudson/tasks/junit/storage/TestResultStorageTest.java
Labels: enhancement

#146 Mark types in hudson.tasks.junit.storage package as beta
  src/main/java/hudson/tasks/junit/storage/TestResultImpl.java
  src/main/java/hudson/tasks/junit/storage/TestResultStorage.java
Labels: enhancement
