Repository jenkinsci/junit-plugin, pull requests merged in 2021-08, with the labels that each got.

#287 Add link to contribution guidelines to README
  README.md
Labels: documentation

#289 API for history table in pluggable storage, fix JENKINS-64585, JENKINS-64586, JENKINS-64587
  pom.xml
  src/main/java/hudson/tasks/junit/History.java
  src/main/java/hudson/tasks/junit/HistoryTestResultSummary.java
  src/main/java/io/jenkins/plugins/junit/storage/TestResultImpl.java
  src/main/resources/hudson/tasks/junit/History/index.jelly
  src/main/webapp/history/history.js
  src/test/java/io/jenkins/plugins/junit/storage/TestResultStorageJunitTest.java
Labels: enhancement, bugfix

#290 Fix enforcer
  pom.xml
Labels: skip-changelog

#291 Code Improvements
  pom.xml
  src/main/java/hudson/tasks/junit/CaseResult.java
  src/main/java/hudson/tasks/junit/ClassResult.java
  src/main/java/hudson/tasks/junit/JUnitResultArchiver.java
  src/main/java/hudson/tasks/junit/PackageResult.java
  src/main/java/hudson/tasks/junit/SuiteResult.java
  src/main/java/hudson/tasks/junit/TestDataPublisher.java
  src/main/java/hudson/tasks/junit/TestDurationResultSummary.java
  src/main/java/hudson/tasks/junit/TestResult.java
  src/main/java/hudson/tasks/junit/TestResultAction.java
  src/main/java/hudson/tasks/junit/pipeline/JUnitResultsStep.java
  src/main/java/hudson/tasks/test/AbstractTestResultAction.java
  src/main/java/hudson/tasks/test/AggregatedTestResultAction.java
  src/main/java/hudson/tasks/test/AggregatedTestResultPublisher.java
  src/main/java/hudson/tasks/test/DefaultTestResultParserImpl.java
  src/main/java/hudson/tasks/test/SimpleCaseResult.java
  src/main/java/hudson/tasks/test/TestObject.java
  src/main/java/hudson/tasks/test/TestResultDurationChart.java
  src/main/java/hudson/tasks/test/TestResultTrendSeriesBuilder.java
  src/main/java/io/jenkins/plugins/junit/storage/JunitTestResultStorage.java
  src/test/java/hudson/tasks/junit/CaseResultTest.java
  src/test/java/hudson/tasks/junit/CaseResultUnitTest.java
  src/test/java/hudson/tasks/junit/ClassResultTest.java
  src/test/java/hudson/tasks/junit/HistoryTest.java
  src/test/java/hudson/tasks/junit/JUnitParserTest.java
  src/test/java/hudson/tasks/junit/JUnitResultArchiverTest.java
  src/test/java/hudson/tasks/junit/SuiteResult2Test.java
  src/test/java/hudson/tasks/junit/SuiteResultTest.java
  src/test/java/hudson/tasks/junit/TestNameTransformerTest.java
  src/test/java/hudson/tasks/junit/TestResultLinksTest.java
  src/test/java/hudson/tasks/junit/TestResultPublishingTest.java
  src/test/java/hudson/tasks/junit/TestResultTest.java
  src/test/java/hudson/tasks/junit/pipeline/JUnitResultsStepTest.java
  src/test/java/hudson/tasks/test/AggregatedTestResultPublisherTest.java
  src/test/java/hudson/tasks/test/BuildStatusSummaryTest.java
  src/test/java/hudson/tasks/test/TestObjectTest.java
  src/test/java/hudson/tasks/test/helper/AbstractTestResultLink.java
  src/test/java/hudson/tasks/test/helper/BuildPage.java
  src/test/java/hudson/tasks/test/helper/LatestTestResultLink.java
  src/test/java/hudson/tasks/test/helper/TestResultLink.java
  src/test/java/io/jenkins/plugins/junit/storage/TestResultStorageJunitTest.java
Labels: chore

#292 Improve handling of missing & empty test result files
  src/main/java/hudson/tasks/junit/JUnitParser.java
  src/main/java/hudson/tasks/junit/JUnitResultArchiver.java
  src/test/java/hudson/tasks/junit/JUnitResultArchiverTest.java
Labels: bug
