Repository jenkinsci/junit-plugin, pull requests merged in 2022-10, with the labels that each got.

#438 Use ionicons in test result overview
  pom.xml
  src/main/resources/hudson/tasks/junit/CaseResult/summary.jelly
  src/main/resources/lib/hudson/test/failed-test.jelly
Labels: enhancement

#440 Switch bootstrap5-api and echarts-api to get versions from bom
  pom.xml
Labels: chore

#441 Run tests on Java 11 & 17
  Jenkinsfile
Labels: chore

#439 [JENKINS-69658] Move internal `script` block in "failed-test.jelly" to external file
  src/main/resources/lib/hudson/test/failed-test.jelly
  src/main/resources/lib/hudson/test/js/failureSummary.js
Labels: enhancement, hacktoberfest

#445 [JENKINS-69657] Un-inlining floatingBox.jelly for CSP compliance
  src/main/resources/hudson/tasks/test/TestResultProjectAction/floatingBox.jelly
  src/main/resources/hudson/tasks/test/TestResultProjectAction/junit-trend-color-switcher.js
Labels: enhancement

#444 [JENKINS-69656] Un-inlining AbstractTestResultAction/summary.jelly for CSP compliance
  src/main/resources/hudson/tasks/test/AbstractTestResultAction/show-failures.js
  src/main/resources/hudson/tasks/test/AbstractTestResultAction/summary.jelly
Labels: enhancement
