Repository jenkinsci/junit-plugin, pull requests merged in 2022-04, with the labels that each got.

#370 Make TestResult#getSuites(String) really null-safe
  src/main/java/hudson/tasks/junit/TestResult.java
Labels: bug

#375 pin jackson2-api temporarily
  pom.xml
Labels: chore

#376 Bump plugin BOM from 1210.vcd41f6657f03 to 1280.vd669827e38cd
  pom.xml
Labels: dependencies

#377 Update plugin POM and BOM
  pom.xml
  src/test/java/io/jenkins/plugins/junit/storage/TestResultStorageJunitTest.java
Labels: developer
