Repository jenkinsci/junit-plugin, pull requests merged in 2022-03, with the labels that each got.

#362 Switch `HudsonTestCase` to `JenkinsRule` in test
  src/test/java/hudson/tasks/test/TestResultExtensionTest.java
Labels: tests

#363 Enable release drafter via GitHub action
  .github/workflows/release-drafter.yml
Labels: chore

#369 Disambiguate a case where multiple test suites have the same name
  src/main/java/hudson/tasks/junit/CaseResult.java
  src/main/java/hudson/tasks/junit/TestResult.java
  src/test/java/hudson/tasks/junit/pipeline/JUnitResultsStepTest.java
  src/test/resources/hudson/tasks/junit/pipeline/ageReset-1.xml
  src/test/resources/hudson/tasks/junit/pipeline/ageReset-2.xml
Labels: bug
