Repository jenkinsci/junit-plugin, pull requests merged in 2022-05, with the labels that each got.

#272 Upgrade trends and detail views to Bootstrap 5
  pom.xml
  src/main/java/hudson/tasks/junit/History.java
  src/main/java/hudson/tasks/test/TestResultDurationChart.java
  src/main/java/hudson/tasks/test/TestResultProjectAction.java
  src/main/java/hudson/tasks/test/TestResultTrendChart.java
  src/main/resources/hudson/tasks/junit/History/index.jelly
  src/main/resources/hudson/tasks/test/TestResultProjectAction/floatingBox.jelly
  src/main/webapp/history/history.css
  src/main/webapp/history/history.js
  src/test/java/hudson/tasks/junit/JUnitResultArchiverTest.java
  src/test/java/hudson/tasks/junit/TestResultPublishingTest.java
  src/test/java/hudson/tasks/test/AggregatedTestResultPublisherTest.java
  src/test/java/hudson/tasks/test/helper/WebClientFactory.java
Labels: enhancement

#286 Add color configuration of trend chart (show passed tests in green or blue )
  src/main/java/hudson/tasks/test/TestResultProjectAction.java
  src/main/java/hudson/tasks/test/TestResultTrendChart.java
  src/main/resources/hudson/tasks/test/TestResultProjectAction/floatingBox.jelly
Labels: feature

#381 Improve jenkins-table layout
  src/main/resources/hudson/tasks/junit/CaseResult/list.jelly
  src/main/resources/hudson/tasks/junit/ClassResult/body.jelly
  src/main/resources/hudson/tasks/junit/ClassResult/list.jelly
  src/main/resources/hudson/tasks/junit/History/index.jelly
  src/main/resources/hudson/tasks/test/AggregatedTestResultPublisher/TestResultAction/index.jelly
  src/main/resources/hudson/tasks/test/MetaTabulatedResult/body.jelly
  src/main/resources/hudson/tasks/test/MetaTabulatedResult/list.jelly
  src/main/resources/lib/hudson/test/aggregated-failed-tests.jelly
  src/test/resources/hudson/tasks/test/TrivialTestResult/body.jelly
Labels: bug

#386 Add information about skipMarkingBuildUnstable in README.MD
  README.md
Labels: documentation

#387 Do not fail build when checks publishing breaks
  src/main/java/hudson/tasks/junit/JUnitResultArchiver.java
Labels: bug

#396 Switch connection to use https from deprecate git protocol
  pom.xml
Labels: chore
