Repository jenkinsci/junit-plugin, pull requests merged in 2024-08, with the labels that each got.

#632 Slim down JPI
  pom.xml
Labels: internal

#635 Skip 3.x of parallel-collectors in renovate
  .github/renovate.json
Labels: chore

#640 Improve recently added log messages by adding context to indicate which build is relevant
  src/main/java/hudson/tasks/junit/CaseResult.java
  src/main/java/hudson/tasks/junit/SuiteResult.java
  src/main/java/hudson/tasks/junit/TestResult.java
  src/main/java/hudson/tasks/junit/TestResultAction.java
Labels: enhancement
