Repository jenkinsci/junit-plugin, pull requests merged in 2025-02, with the labels that each got.

#671 Migrate from EE 8 to EE 9
  pom.xml
  src/main/java/hudson/tasks/junit/CaseResult.java
  src/main/java/hudson/tasks/junit/ClassResult.java
  src/main/java/hudson/tasks/junit/PackageResult.java
  src/main/java/hudson/tasks/junit/TestResult.java
  src/main/java/hudson/tasks/test/AggregatedTestResultPublisher.java
  src/main/java/hudson/tasks/test/TestObject.java
  src/main/java/hudson/tasks/test/TestResultProjectAction.java
  src/main/java/io/jenkins/plugins/junit/storage/JunitTestResultStorageConfiguration.java
  src/main/resources/hudson/tasks/junit/History/index.jelly
  src/main/resources/hudson/tasks/test/TestObject/sidepanel.jelly
  src/main/resources/hudson/tasks/test/TestResultProjectAction/index.jelly
  src/test/java/io/jenkins/plugins/junit/storage/benchmarks/TrendGraphBenchmark.java
Labels: internal

#675 Reuse title information as summary
  src/main/java/io/jenkins/plugins/junit/checks/JUnitChecksPublisher.java
  src/test/java/io/jenkins/plugins/junit/checks/JUnitChecksPublisherTest.java
Labels: enhancement

#677 Fix pipeline snippet generator for StdIO retention
  src/main/java/hudson/tasks/junit/pipeline/JUnitResultsStep.java
Labels: bug
