Repository jenkinsci/junit-plugin, pull requests merged in 2025-04, with the labels that each got.

#688 Remove 'pane-header' class usage
  src/main/resources/hudson/tasks/junit/CaseResult/list.jelly
  src/main/resources/hudson/tasks/junit/ClassResult/body.jelly
  src/main/resources/hudson/tasks/junit/ClassResult/list.jelly
  src/main/resources/hudson/tasks/junit/History/index.jelly
  src/main/resources/hudson/tasks/test/AggregatedTestResultPublisher/TestResultAction/index.jelly
  src/main/resources/hudson/tasks/test/MetaTabulatedResult/body.jelly
  src/main/resources/hudson/tasks/test/MetaTabulatedResult/list.jelly
  src/main/resources/lib/hudson/test/aggregated-failed-tests.jelly
Labels: enhancement

#690 [JENKINS-75465] Update HistoryTest.zip and TestResultPublishingTest.zip file with numerical build directories
  src/test/resources/hudson/tasks/junit/HistoryTest.zip
  src/test/resources/hudson/tasks/junit/TestResultPublishingTest.zip
Labels: developer

#698 Migrate tests to JUnit5
  src/test/java/hudson/tasks/junit/CaseResultTest.java
  src/test/java/hudson/tasks/junit/CaseResultUnitTest.java
  src/test/java/hudson/tasks/junit/ClassResultTest.java
  src/test/java/hudson/tasks/junit/CustomColumnsTest.java
  src/test/java/hudson/tasks/junit/HistoryTest.java
  src/test/java/hudson/tasks/junit/JUnitParserTest.java
  src/test/java/hudson/tasks/junit/JUnitResultArchiverTest.java
  src/test/java/hudson/tasks/junit/SimpleLinearRegressionTest.java
  src/test/java/hudson/tasks/junit/SuiteResult2Test.java
  src/test/java/hudson/tasks/junit/SuiteResultTest.java
  src/test/java/hudson/tasks/junit/TestNameTransformerTest.java
  src/test/java/hudson/tasks/junit/TestResultLinksTest.java
  src/test/java/hudson/tasks/junit/TestResultPublishingTest.java
  src/test/java/hudson/tasks/junit/TestResultTest.java
  src/test/java/hudson/tasks/junit/pipeline/JUnitResultsStepTest.java
  src/test/java/hudson/tasks/junit/rot13/Rot13Publisher.java
  src/test/java/hudson/tasks/test/AggregatedTestResultPublisherTest.java
  src/test/java/hudson/tasks/test/BuildStatusSummaryTest.java
  src/test/java/hudson/tasks/test/TestObjectTest.java
  src/test/java/hudson/tasks/test/TestReportUiTest.java
  src/test/java/hudson/tasks/test/TestResultExtensionTest.java
  src/test/java/hudson/tasks/test/TestResultTrendChartTest.java
  src/test/java/hudson/tasks/test/helper/AbstractPage.java
  src/test/java/io/jenkins/plugins/junit/checks/JUnitChecksPublisherTest.java
  src/test/java/io/jenkins/plugins/junit/storage/JunitTestResultStorageConfigurationTest.java
  src/test/java/io/jenkins/plugins/junit/storage/TestResultStorageJunitTest.java
  src/test/java/io/jenkins/plugins/junit/storage/benchmarks/BenchmarkRunner.java
  src/test/java/io/jenkins/plugins/junit/storage/benchmarks/TrendGraphBenchmark.java
Labels: test
